### ISSUE TITLE
Documentation/website mentions

### ISSUE THREAD

**Issue by MFernstrom** [RapidInfoSys/Rapid#3]
The info box for Web services mentions

> Webservices can be used by your Rapid application and external systems. 
They can be invoked in SOAP or JSON. 
Request messages are validated against the schema before processing.
Advanced users can add their own adapters for other types. 

But the drop down only shows SQL and Java.

I'm also not sure where to find information about creating custom adapters.

**Comment by gareth-edwards** [comment]
Hi Marcus

The webservices tab you're looking at is for Rapid to host webservice APIs. To call them use the webservice action in the Design tool.

**Comment by MFernstrom** [comment]
Oh, hah! Yep, there it is, thanks!
