### ISSUE TITLE
Lacking examples/docs

### ISSUE THREAD

**Issue by MFernstrom** [RapidInfoSys/Rapid#4]
I've seen mentions of integration with LDAP and databases, but no examples or documentation for how to do that.

**Comment by gareth-edwards** [comment]
Hi Marcus,

Yeah, sorry, we're a small start-up and a bit light on documentation right now. We do the LDAP as a paid-for Enterprise service but adding database drivers are pretty easy if you look in WEB-INF/databases

**Comment by MFernstrom** [comment]
No worries, if my test runs turn out nice I'll be making some tutorials myself, still wanted to put out the question/request.
